#!/usr/bin/env python3
from __future__ import annotations

import argparse
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path
from uuid import uuid4

from sqlalchemy import delete, select
from sqlalchemy.orm import Session

PROJECT_ROOT = Path(__file__).resolve().parents[1]
BACKEND_ROOT = PROJECT_ROOT / "backend"
if str(BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(BACKEND_ROOT))

from app.core.database import Base, SessionLocal, engine  # noqa: E402
from app.models.db import Case, DiagramSpec, Evidence, JobRun, Report, ReportExport, ReportSection, WorkflowRun  # noqa: E402
from app.services.network_service import NetworkService  # noqa: E402


DIAGRAM_TYPES = ("attack_flow", "fund_flow", "evidence_map")
JOB_NAMES = (
    "environment_check_worker",
    "tx_discovery_worker",
    "txanalyzer_worker",
    "decode_worker",
    "fund_flow_worker",
    "loss_calculator_worker",
    "rca_agent_worker",
    "report_worker",
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Seed synthetic RCA Workbench load-test data.")
    parser.add_argument("--cases", type=int, default=5000)
    parser.add_argument("--evidence", type=int, default=100000)
    parser.add_argument("--jobs", type=int, default=20000)
    parser.add_argument("--reports", type=int, default=5000)
    parser.add_argument("--diagrams", type=int, default=15000)
    parser.add_argument("--exports", type=int, default=5000)
    parser.add_argument("--reset-generated", action="store_true", help="Delete rows generated by this script before seeding.")
    return parser.parse_args()


def chunked(rows: list[dict], size: int = 1000):
    for index in range(0, len(rows), size):
        yield rows[index : index + size]


def reset_generated(db: Session) -> int:
    case_ids = list(db.scalars(select(Case.id).where(Case.title.like("[perf]%"))).all())
    if not case_ids:
        return 0
    report_ids = list(db.scalars(select(Report.id).where(Report.case_id.in_(case_ids))).all())
    for model, predicate in [
        (ReportExport, ReportExport.report_id.in_(report_ids) if report_ids else ReportExport.report_id == "__none__"),
        (ReportSection, ReportSection.report_id.in_(report_ids) if report_ids else ReportSection.report_id == "__none__"),
        (DiagramSpec, DiagramSpec.case_id.in_(case_ids)),
        (Report, Report.case_id.in_(case_ids)),
        (WorkflowRun, WorkflowRun.case_id.in_(case_ids)),
        (JobRun, JobRun.case_id.in_(case_ids)),
        (Evidence, Evidence.case_id.in_(case_ids)),
        (Case, Case.id.in_(case_ids)),
    ]:
        db.execute(delete(model).where(predicate))
    db.commit()
    return len(case_ids)


def bulk_insert(db: Session, model, rows: list[dict]) -> None:
    for batch in chunked(rows):
        db.bulk_insert_mappings(model, batch)
        db.commit()


def seed_performance_data(
    db: Session,
    case_count: int,
    evidence_count: int,
    job_count: int,
    report_count: int,
    diagram_count: int,
    export_count: int,
    reset: bool = False,
) -> dict[str, int]:
    if reset:
        reset_generated(db)
    if case_count < 1:
        raise ValueError("--cases must be at least 1")
    networks = NetworkService(db).list_networks()
    if not networks:
        NetworkService(db).seed_from_config()
        networks = NetworkService(db).list_networks()
    if not networks:
        raise RuntimeError("No networks configured. Seed network_config before performance data.")

    now = datetime.now(timezone.utc)
    case_ids = [str(uuid4()) for _ in range(case_count)]
    case_rows = []
    for index, case_id in enumerate(case_ids):
        network = networks[index % len(networks)]
        created = now - timedelta(minutes=index)
        case_rows.append(
            {
                "id": case_id,
                "title": f"[perf] RCA load case {index + 1:05d}",
                "network_key": network.key,
                "seed_type": "transaction",
                "seed_value": f"0x{index:064x}",
                "time_window_hours": 6,
                "depth": "full",
                "status": "REPORT_DRAFTED",
                "severity": "high" if index % 11 == 0 else "medium",
                "attack_type": ["oracle_price_manipulation", "cross_contract_reentrancy", "reward_accounting"][index % 3],
                "root_cause_one_liner": "Synthetic load-test case used to validate pagination and summary endpoints.",
                "loss_usd": float((index % 1000) * 1000),
                "confidence": "medium",
                "language": "zh-CN",
                "created_by": "performance_seed",
                "created_at": created,
                "updated_at": created,
            }
        )
    bulk_insert(db, Case, case_rows)

    evidence_rows = []
    for index in range(evidence_count):
        case_id = case_ids[index % case_count]
        evidence_rows.append(
            {
                "id": str(uuid4()),
                "case_id": case_id,
                "source_type": "receipt_log" if index % 2 == 0 else "derived_graph",
                "producer": "performance_seed",
                "claim_key": "fund_flow_edges" if index % 3 == 0 else "synthetic_evidence",
                "raw_path": f"perf://{case_id}/evidence/{index}",
                "decoded": {
                    "fund_flow_edges": [
                        {
                            "from": f"0x{index % 17:040x}",
                            "to": f"0x{(index + 1) % 23:040x}",
                            "asset": "USDC",
                            "amount": str((index % 1000) * 10),
                            "confidence": "high",
                        }
                    ]
                },
                "confidence": "high" if index % 5 == 0 else "medium",
                "created_at": now - timedelta(seconds=index),
            }
        )
    bulk_insert(db, Evidence, evidence_rows)

    job_rows = []
    for index in range(job_count):
        case_id = case_ids[index % case_count]
        job_rows.append(
            {
                "id": str(uuid4()),
                "case_id": case_id,
                "job_name": JOB_NAMES[index % len(JOB_NAMES)],
                "status": "success" if index % 31 else "partial",
                "input": {"workflow_run_id": f"perf-{index % case_count}"},
                "output": {"synthetic": True, "index": index},
                "error": None,
                "started_at": now - timedelta(seconds=index + 2),
                "ended_at": now - timedelta(seconds=index),
                "created_at": now - timedelta(seconds=index + 3),
            }
        )
    bulk_insert(db, JobRun, job_rows)

    report_ids = [str(uuid4()) for _ in range(report_count)]
    report_rows = []
    section_rows = []
    for index, report_id in enumerate(report_ids):
        case_id = case_ids[index % case_count]
        version = index // case_count + 1
        report_rows.append(
            {
                "id": report_id,
                "case_id": case_id,
                "version": version,
                "language": "zh-CN",
                "format": "markdown",
                "status": "draft",
                "object_path": f"perf://{case_id}/reports/report_v{version}.md",
                "content_hash": f"perf-{index}",
                "evidence_coverage": {"synthetic": {"coverage": 1.0}},
                "metadata_json": {"generator": "performance_seed"},
                "created_by": "performance_seed",
                "created_at": now - timedelta(seconds=index),
                "updated_at": now - timedelta(seconds=index),
            }
        )
        section_rows.append(
            {
                "id": str(uuid4()),
                "report_id": report_id,
                "section_order": 1,
                "title": "TL;DR",
                "body_markdown": "Synthetic performance report section.",
                "evidence_ids": [],
                "coverage": 1.0,
                "status": "supported",
                "created_at": now - timedelta(seconds=index),
            }
        )
    bulk_insert(db, Report, report_rows)
    bulk_insert(db, ReportSection, section_rows)

    diagram_rows = []
    diagram_count = min(diagram_count, case_count * len(DIAGRAM_TYPES))
    for index in range(diagram_count):
        case_id = case_ids[index // len(DIAGRAM_TYPES)]
        diagram_type = DIAGRAM_TYPES[index % len(DIAGRAM_TYPES)]
        report_id = report_ids[index % report_count] if report_count else None
        diagram_rows.append(
            {
                "id": str(uuid4()),
                "case_id": case_id,
                "report_id": report_id,
                "diagram_type": diagram_type,
                "title": diagram_type.replace("_", " ").title(),
                "mermaid_source": "flowchart LR\n  A[Source] --> B[Target]",
                "nodes_edges_json": {"nodes": [], "edges": []},
                "evidence_ids": [],
                "confidence": "medium",
                "source_type": "synthetic_performance_seed",
                "object_path": f"perf://{case_id}/diagrams/{diagram_type}.json",
                "content_hash": f"perf-diagram-{index}",
                "created_by": "performance_seed",
                "created_at": now - timedelta(seconds=index),
                "updated_at": now - timedelta(seconds=index),
            }
        )
    bulk_insert(db, DiagramSpec, diagram_rows)

    export_rows = []
    export_count = min(export_count, report_count)
    for index in range(export_count):
        report_id = report_ids[index]
        export_rows.append(
            {
                "id": str(uuid4()),
                "report_id": report_id,
                "format": "pdf",
                "status": "success",
                "object_path": f"perf://reports/{report_id}/export.pdf",
                "content_hash": f"perf-pdf-{index}",
                "error": None,
                "metadata_json": {"synthetic": True},
                "created_by": "performance_seed",
                "created_at": now - timedelta(seconds=index),
                "updated_at": now - timedelta(seconds=index),
            }
        )
    bulk_insert(db, ReportExport, export_rows)

    return {
        "cases": case_count,
        "evidence": evidence_count,
        "jobs": job_count,
        "reports": report_count,
        "diagrams": diagram_count,
        "exports": export_count,
    }


def main() -> None:
    args = parse_args()
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    try:
        result = seed_performance_data(
            db,
            args.cases,
            args.evidence,
            args.jobs,
            args.reports,
            args.diagrams,
            args.exports,
            reset=args.reset_generated,
        )
    finally:
        db.close()
    print(result)


if __name__ == "__main__":
    main()
